#!/bin/bash

PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/local/lib/pkgconfig:/usr/lib/pkgconfig CC="gcc-4.0 -m32" CXX="g++-4.0 -m32" ./configure --prefix=/usr/local --with-wxconfig-path=/Users/jesse/src/wxMac-2.8.7/wx-config --with-macosx-sdk --with-macosx-min-version=10.4 
